### ISSUE TITLE
Is this working :o?

### ISSUE THREAD

**Issue by Hedronmx** [winters-brown/whatsapp-web#1]
Is this really working? I am currently using Whatsie and I am craving a elementary os theme for that.

Can I install this?

**Comment by winters-brown** [comment]
Yes this does work so far, you are able to install i just updated the readme. If you need any help installing send me a message :+1:

**Comment by Hedronmx** [comment]
I get this error when running ninja. I fixed it by removing the build folder of the repo. I suggest deleting it from the repo
```
[0/1] Regenerating build files.
Error during basic setup:

[Errno 13] Permission denied: '/home/winters-brown'
FAILED: build.ninja 
/usr/bin/meson --internal regenerate /home/winters-brown/Documents/Programming/whatsapp-web /home/winters-brown/Documents/Programming/whatsapp-web/build --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```
